-- P1-01..P1-04 · Quiz content: profiles, quizzes, questions, published versions, media bucket.
-- Design: docs/03-data-model.md. RLS tests: supabase/tests/content.test.ts.

-- ─── Types ────────────────────────────────────────────────────────────────────

create type public.quiz_visibility as enum ('private', 'unlisted', 'public');

-- ─── Helpers ──────────────────────────────────────────────────────────────────

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ─── Profiles (hosts) ─────────────────────────────────────────────────────────

create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  avatar_url   text,
  created_at   timestamptz not null default now()
);

-- New sign-ups get a profile. Anonymous users (quiz participants, P2) don't.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(new.is_anonymous, false) then
    return new;
  end if;
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    left(coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Guru'
    ), 80),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── Quizzes ──────────────────────────────────────────────────────────────────

create table public.quizzes (
  id                    uuid primary key default gen_random_uuid(),
  owner_id              uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  title                 text not null default '' check (char_length(title) <= 150),
  description           text not null default '' check (char_length(description) <= 2000),
  cover_url             text,
  theme                 jsonb not null default '{}',
  visibility            public.quiz_visibility not null default 'private',
  slug                  text unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  embed_allowed_origins text[] not null default '{}',
  -- Bumped by every save; saves and publishes must name the revision they build on.
  draft_revision        int not null default 0,
  -- draft_revision that the latest version was published from (null = never published).
  published_revision    int,
  latest_version        int,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index quizzes_owner_updated_idx on public.quizzes (owner_id, updated_at desc);

create trigger quizzes_set_updated_at
  before update on public.quizzes
  for each row execute function public.set_updated_at();

-- ─── Questions (the editable draft) ───────────────────────────────────────────

create table public.questions (
  id           uuid primary key,  -- generated by the editor (crypto.randomUUID)
  quiz_id      uuid not null references public.quizzes (id) on delete cascade,
  position     int  not null check (position >= 0),
  type         text not null check (type ~ '^[a-z][a-z_]*$'),
  prompt       text not null default '' check (char_length(prompt) <= 2000),
  help         text not null default '' check (char_length(help) <= 1000),
  media        jsonb not null default '[]' check (jsonb_typeof(media) = 'array'),
  config       jsonb not null check (jsonb_typeof(config) = 'object'),
  time_limit_s int check (time_limit_s between 5 and 600),
  points       int  not null default 1000 check (points between 0 and 10000),
  explanation  text not null default '' check (char_length(explanation) <= 2000),
  tags         text[] not null default '{}',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index questions_quiz_position_idx on public.questions (quiz_id, position);

create trigger questions_set_updated_at
  before update on public.questions
  for each row execute function public.set_updated_at();

-- ─── Published versions (immutable snapshots) ─────────────────────────────────

create table public.quiz_versions (
  id           uuid primary key default gen_random_uuid(),
  quiz_id      uuid not null references public.quizzes (id) on delete cascade,
  version      int  not null check (version >= 1),
  snapshot     jsonb not null,
  published_at timestamptz not null default now(),
  unique (quiz_id, version)
);

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Participants never read these tables directly; they get stripped payloads
-- through server code (docs/02-architecture.md#keamanan).

alter table public.profiles      enable row level security;
alter table public.quizzes       enable row level security;
alter table public.questions     enable row level security;
alter table public.quiz_versions enable row level security;

create policy "profiles: read own" on public.profiles
  for select to authenticated using (id = (select auth.uid()));
create policy "profiles: update own" on public.profiles
  for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

create policy "quizzes: owner reads" on public.quizzes
  for select to authenticated using (owner_id = (select auth.uid()));
create policy "quizzes: owner creates" on public.quizzes
  for insert to authenticated with check (owner_id = (select auth.uid()));
create policy "quizzes: owner updates" on public.quizzes
  for update to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "quizzes: owner deletes" on public.quizzes
  for delete to authenticated using (owner_id = (select auth.uid()));

create function public.owns_quiz(p_quiz_id uuid)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1 from public.quizzes q where q.id = p_quiz_id and q.owner_id = (select auth.uid())
  );
$$;

create policy "questions: owner reads" on public.questions
  for select to authenticated using (public.owns_quiz(quiz_id));
create policy "questions: owner creates" on public.questions
  for insert to authenticated with check (public.owns_quiz(quiz_id));
create policy "questions: owner updates" on public.questions
  for update to authenticated using (public.owns_quiz(quiz_id)) with check (public.owns_quiz(quiz_id));
create policy "questions: owner deletes" on public.questions
  for delete to authenticated using (public.owns_quiz(quiz_id));

-- Versions are written only by publish_quiz() and never updated or deleted
-- (removal happens through the quiz's ON DELETE CASCADE).
create policy "quiz_versions: owner reads" on public.quiz_versions
  for select to authenticated using (public.owns_quiz(quiz_id));
create policy "quiz_versions: owner creates" on public.quiz_versions
  for insert to authenticated with check (public.owns_quiz(quiz_id));

revoke all on public.profiles, public.quizzes, public.questions, public.quiz_versions from anon;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.quizzes, public.questions to authenticated;
grant select, insert on public.quiz_versions to authenticated;

-- ─── Autosave ─────────────────────────────────────────────────────────────────

-- Replace the whole draft in one transaction: quiz meta + ordered question list.
-- Questions missing from p_questions are deleted. Raises 'revision_conflict' when
-- p_base_revision is stale (e.g. edited in another tab) and 'quiz_not_found' when
-- the quiz doesn't exist or isn't the caller's. Returns the new revision.
create function public.save_quiz_draft(
  p_quiz_id       uuid,
  p_base_revision int,
  p_quiz          jsonb,  -- { title, description, cover_url, theme }
  p_questions     jsonb   -- [{ id, type, prompt, help, media, config, time_limit_s, points, explanation, tags }]
)
returns int
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_revision int;
begin
  if jsonb_typeof(p_questions) <> 'array' then
    raise exception 'p_questions must be a JSON array' using errcode = '22023';
  end if;

  update public.quizzes q
     set title          = coalesce(p_quiz ->> 'title', q.title),
         description    = coalesce(p_quiz ->> 'description', q.description),
         cover_url      = case when p_quiz ? 'cover_url' then p_quiz ->> 'cover_url' else q.cover_url end,
         theme          = coalesce(p_quiz -> 'theme', q.theme),
         draft_revision = q.draft_revision + 1
   where q.id = p_quiz_id
     and q.draft_revision = p_base_revision
  returning q.draft_revision into v_revision;

  if v_revision is null then
    if exists (select 1 from public.quizzes where id = p_quiz_id) then
      raise exception 'revision_conflict' using errcode = 'P0001';
    end if;
    raise exception 'quiz_not_found' using errcode = 'P0002';
  end if;

  delete from public.questions
   where quiz_id = p_quiz_id
     and id not in (select (e ->> 'id')::uuid from jsonb_array_elements(p_questions) as e);

  insert into public.questions as cur
    (id, quiz_id, position, type, prompt, help, media, config, time_limit_s, points, explanation, tags)
  select (e ->> 'id')::uuid,
         p_quiz_id,
         (t.ord - 1)::int,
         e ->> 'type',
         coalesce(e ->> 'prompt', ''),
         coalesce(e ->> 'help', ''),
         coalesce(e -> 'media', '[]'),
         e -> 'config',
         (e ->> 'time_limit_s')::int,
         coalesce((e ->> 'points')::int, 1000),
         coalesce(e ->> 'explanation', ''),
         coalesce(array(select jsonb_array_elements_text(e -> 'tags')), '{}')
    from jsonb_array_elements(p_questions) with ordinality as t(e, ord)
  on conflict (id) do update
     set position     = excluded.position,
         type         = excluded.type,
         prompt       = excluded.prompt,
         help         = excluded.help,
         media        = excluded.media,
         config       = excluded.config,
         time_limit_s = excluded.time_limit_s,
         points       = excluded.points,
         explanation  = excluded.explanation,
         tags         = excluded.tags
   -- An id that already belongs to another quiz is left alone (never moved).
   where cur.quiz_id = p_quiz_id;

  return v_revision;
end;
$$;

-- ─── Publish ──────────────────────────────────────────────────────────────────

-- Snapshot the saved draft as the next immutable version. The caller validates
-- the draft first (validateQuiz in TS) and passes the revision it validated, so
-- the snapshot is exactly what passed validation.
create function public.publish_quiz(p_quiz_id uuid, p_base_revision int, p_slug text)
returns table (version int, slug text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_quiz    public.quizzes;
  v_version int;
begin
  select * into v_quiz from public.quizzes where id = p_quiz_id for update;
  if not found then
    raise exception 'quiz_not_found' using errcode = 'P0002';
  end if;
  if v_quiz.draft_revision <> p_base_revision then
    raise exception 'revision_conflict' using errcode = 'P0001';
  end if;

  v_version := coalesce(v_quiz.latest_version, 0) + 1;

  insert into public.quiz_versions (quiz_id, version, snapshot)
  values (
    p_quiz_id,
    v_version,
    jsonb_build_object(
      'quiz', jsonb_build_object(
        'id', v_quiz.id,
        'title', v_quiz.title,
        'description', v_quiz.description,
        'cover_url', v_quiz.cover_url,
        'theme', v_quiz.theme
      ),
      'questions', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'id', q.id,
                 'type', q.type,
                 'prompt', q.prompt,
                 'help', q.help,
                 'media', q.media,
                 'config', q.config,
                 'time_limit_s', q.time_limit_s,
                 'points', q.points,
                 'explanation', q.explanation,
                 'tags', to_jsonb(q.tags)
               ) order by q.position)
          from public.questions q
         where q.quiz_id = p_quiz_id
      ), '[]'::jsonb)
    )
  );

  update public.quizzes q
     set latest_version     = v_version,
         published_revision = v_quiz.draft_revision,
         slug               = coalesce(q.slug, p_slug)
   where q.id = p_quiz_id;

  return query select v_version, coalesce(v_quiz.slug, p_slug);
end;
$$;

revoke all on function public.save_quiz_draft(uuid, int, jsonb, jsonb) from public, anon;
revoke all on function public.publish_quiz(uuid, int, text) from public, anon;
grant execute on function public.save_quiz_draft(uuid, int, jsonb, jsonb) to authenticated;
grant execute on function public.publish_quiz(uuid, int, text) to authenticated;

-- ─── Media storage ────────────────────────────────────────────────────────────
-- Public bucket: participants (anonymous) must load question images and audio.
-- Paths are {owner_id}/{quiz_id}/{file}; only the owner may write under their folder.
-- Per-kind size limits (images 5 MB) are enforced by the upload code.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'quiz-media',
  'quiz-media',
  true,
  10485760,
  array[
    'image/png', 'image/jpeg', 'image/webp', 'image/gif',
    'audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/webm'
  ]
);

create policy "quiz-media: owner uploads" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'quiz-media' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "quiz-media: owner updates" on storage.objects
  for update to authenticated
  using (bucket_id = 'quiz-media' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "quiz-media: owner deletes" on storage.objects
  for delete to authenticated
  using (bucket_id = 'quiz-media' and (storage.foldername(name))[1] = (select auth.uid())::text);
